import NavBar from "@/components/NavBar";
import "./globals.css";
import { Inter, Open_Sans } from "next/font/google";
import localFont from "@next/font/local";
import clsx from "clsx";

export const metadata = {
  title: "Remix - Build Better Websites",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

// const founders = localFont({
//   src: [
//     {
//       path: "../public/fonts/founders-grotesk-bold.woff2",
//     },
//   ],
//   variable: "--font-founders",
// });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "flex min-h-screen w-full flex-col overflow-x-hidden bg-gray-900 text-gray-200",
          inter.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
